PROCESS BEFORE OUTPUT.
  MODULE STATUS_9000.

PROCESS AFTER INPUT.

  MODULE user_command_exit_command AT EXIT-COMMAND.

  CHAIN.
    FIELD s_9000-entrega MODULE validar_entrega_9000 ON CHAIN-INPUT.
  ENDCHAIN.

  MODULE USER_COMMAND_9000.