PROCESS BEFORE OUTPUT.

MODULE STATUS_9002.

MODULE init_9002.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_9002_POS'
  MODULE TC_9002_POS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_9002_POS_CHANGE_COL_ATTR.
  LOOP AT   T_9002
       INTO S_9002_TABLE
       WITH CONTROL TC_9002_POS
       CURSOR TC_9002_POS-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_9002_POS_CHANGE_FIELD_ATTR
  ENDLOOP.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_9002_POS'
  LOOP AT T_9002.
    CHAIN.
      FIELD S_9002_TABLE-POSNR.
      FIELD S_9002_TABLE-NRO_COT.
      FIELD S_9002_TABLE-MATERIAL_COT.
      FIELD S_9002_TABLE-UNIDAD_COT.
      MODULE TC_9002_POS_MODIFY ON CHAIN-REQUEST.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC_9002_POS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_9002_POS_CHANGE_COL_ATTR.

 MODULE user_command_exit_command AT EXIT-COMMAND.

 MODULE USER_COMMAND_9002.