*&---------------------------------------------------------------------*
*&  Include           ZAA23DT_DYNPROS_COT_TCW
*&---------------------------------------------------------------------*

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_9002_POS' ITSELF
CONTROLS: TC_9002_POS TYPE TABLEVIEW USING SCREEN 9002.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TC_9002_POS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TC_9002_POS_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE T_9002 LINES TC_9002_POS-lines.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TC_9002_POS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TC_9002_POS_MODIFY INPUT.
  MODIFY T_9002
    FROM S_9002_TABLE
    INDEX TC_9002_POS-CURRENT_LINE.
ENDMODULE.